/*MOCK SBA*/

1. SELECT ROW_NUMBER() OVER(ORDER BY o.ORDER_ID) AS 'ORDERS', o.ORDER_ID, u.USER_ID, o.STORE_ID
	FROM users u JOIN orders o ON u.USER_ID = o.USER_ID
	WHERE u.FIRST_NAME LIKE 'Marion%'
	
2. SELECT
	FROM
	WHERE